services:
  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 8090:5432
  Help-desk:
    image: help_desk_app_image
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    ports:
      - 8080:8080
    depends_on:
      - db