spring:
  datasource:
    url: jdbc:postgresql://localhost:8090/postgres
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    ru.edu: debug
  file:
    path: UsersLog.log



  service:
    title: HelpDesk
    description: HelpDesk
    version: 1.0 BETA